### ISSUE TITLE
More than one fragment with the name [spring_web]

### ISSUE THREAD

**Issue by aaronboss** [PopMedNet-Team/Mobile-Application#16]
When I try to run "Debug LabKey Dev", everything seems to load fine until it gets down to starting the labkey component in tomcat.

I get the following issue.

org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/labkey]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:629)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1839)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: More than one fragment with the name [spring_web] was found. This is not legal with relative ordering. See section 8.2.2 2c of the Servlet specification for details. Consider using absolute ordering.
	at org.apache.tomcat.util.descriptor.web.WebXml.orderWebFragments(WebXml.java:2200)
	at org.apache.tomcat.util.descriptor.web.WebXml.orderWebFragments(WebXml.java:2159)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1124)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:769)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 11 more

**Comment by glittomat** [comment]
add <absolute-ordering /> tag to your web.xml just under the <display-name> tag. It should work.

**Comment by glittomat** [comment]
14

add "<absolute-ordering />" tag to your web.xml just under the <display-name> tag. should work.

**Comment by glittomat** [comment]
add <<absolute-ordering/> tag to your  web.xml just under the <display-name> tag.  It should work.

**Comment by glittomat** [comment]
add /* <absolute-ordering/> */ tag to your  web.xml just under the /* <display-name> */ tag.  It should work.

**Comment by glittomat** [comment]
add \* <absolute-ordering/> *\  tag to your  web.xml just under the <display-name> tag.  It should work.

**Comment by glittomat** [comment]
add `<absolute-ordering\>` tag to your  web.xml just under the `<display-name>` tag.  It should work.

**Comment by ankitrajj9** [comment]
Thanks @glittomat . it worked

**Comment by aydincaner** [comment]
Any example webxml, I dont have a project with xmls. I have project with properties, spring boot

**Comment by jokeonmyself** [comment]
> Any example webxml, I dont have a project with xmls. I have project with properties, spring boot

Did you find a solution?

**Comment by aydincaner** [comment]
> > Any example webxml, I dont have a project with xmls. I have project with properties, spring boot
> 
> Did you find a solution?

I think yes.

At last, my xml was like this:
```

<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
                      http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
  version="4.0">

<display-name>XXXX</display-name>
   <absolute-ordering />


```

I only added

`<display-name>XXXX</display-name>
   <absolute-ordering />`

**Comment by jokeonmyself** [comment]
> > > Any example webxml, I dont have a project with xmls. I have project with properties, spring boot
> > 
> > 
> > Did you find a solution?
> 
> I think yes.
> 
> At last, my xml was like this:
> 
> ```
> 
> <web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
>   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>   xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
>                       http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
>   version="4.0">
> 
> <display-name>XXXX</display-name>
>    <absolute-ordering />
> ```
> 
> I only added
> 
> `<display-name>XXXX</display-name> <absolute-ordering />`

You created web.xml for it?

**Comment by aydincaner** [comment]
> > > > Any example webxml, I dont have a project with xmls. I have project with properties, spring boot
> > > 
> > > 
> > > Did you find a solution?
> > 
> > 
> > I think yes.
> > At last, my xml was like this:
> > ```
> > 
> > <web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
> >   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
> >   xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
> >                       http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
> >   version="4.0">
> > 
> > <display-name>XXXX</display-name>
> >    <absolute-ordering />
> > ```
> > 
> > 
> > I only added
> > `<display-name>XXXX</display-name> <absolute-ordering />`
> 
> You created web.xml for it?

NO. There was already a webxml. But no  **display-name** or **absolute-ordering** so i added them to beginning.

**Comment by egovorushkin** [comment]
> add `<absolute-ordering\>` tag to your  web.xml just under the `<display-name>` tag. It should work.

Thank you! Its work for me!

**Comment by aneeshmunnam92** [comment]
`add <absolute-ordering\> tag to your  web.xml just under the <display-name> tag. It should work.`

Worked for me. Will there be any other issues because of ordering?

**Comment by FDA-MyStudies** [comment]
Hi @aaronboss ,
Apologies for the nearly year-long delay in responding.  We only recently required additional funding to support open-source activities for the MyStudies app.  In regards to your original question:

This issue may be because of multiple versions of spring or because some dependencies were missing in your development environment. This issue will be resolved by cleaning the tomcat history or by adding <absolute-ordering\> in web.xml.

**Comment by abhay-kumar-a** [comment]
Thanks @glittomat its working  fine
